---
dependencies:
  - common
  - edxapp_common
  - browsers
  - role: jenkins_common
    jenkins_common_user: '{{ build_jenkins_user }}'
    jenkins_common_version: '{{ build_jenkins_version }}'
    jenkins_common_war_source: '{{ build_jenkins_war_source }}'
    jenkins_common_debian_pkgs: '{{ build_jenkins_debian_pkgs }}'
    jenkins_common_home: '{{ build_jenkins_home }}'
    jenkins_common_git_home: '{{ build_jenkins_git_home }}'
    jenkins_common_config_path: '{{ build_jenkins_config_path }}'
    jenkins_common_configuration_scripts: '{{ build_jenkins_configuration_scripts }}'
    jenkins_common_plugins: '{{ build_jenkins_plugins }}'
    jenkins_common_server_name: '{{ build_jenkins_server_name }}'

  - role: docker-tools
    docker_users:
        - '{{ build_jenkins_user }}'
